((nil . ((eval . (add-to-list 'load-path (expand-file-name ".")))))
 (emacs-lisp-mode . ((fill-column . 100)
                     (indent-tabs-mode . nil)
                     (sentence-end-double-space . nil)
                     (elisp-lint-indent-specs . ((describe . 1)
                                                 (it . 1))))))
